ALTER TYPE "AuditAction" ADD VALUE 'USER_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_STATUS_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE 'USER_PASSWORD_RESET';
